### ISSUE TITLE
Why don't use 20240315_20240316 ?

### ISSUE THREAD

**Issue by xyzroe** [Andrik45719/Z-Stack-firmware#1]
Hello.  
Why is the firmware based on 20230507 but not the latest 20240315_20240316?
https://github.com/Koenkk/Z-Stack-firmware/discussions/496

**Comment by Andrik45719** [comment]
Used last stable public firmware

**Comment by xyzroe** [comment]
Some user [reports](https://t.me/XZG_FW/74/883) "I have tried high baud firmware, got some issues with no-responding-devices. Rolled back to 20240416, this one much more stable." He means 20240315_20240316 for P7. Some other man also confirmed. 

I think it's a good idea to make build based on 20240315_20240316. There is some bug or even bugs in 20230507 as I understood from discussion.

**Comment by Andrik45719** [comment]
Try this one https://github.com/Andrik45719/Z-Stack-firmware/releases/download/20240316/CC1352P7_coordinator_20240316_patched_460800.zip

**Comment by xyzroe** [comment]
Thanks a lot! 
Added your new builds (20240316 and 20221226) to XZG Firmware repo. 
Let's wait until any feedback.
