### ISSUE TITLE
CC2652P7 variant 

### ISSUE THREAD

**Issue by xyzroe** [Andrik45719/Z-Stack-firmware#2]
Could you build your firmware for CC2652P7 ? 
Thanks in advance

**Comment by Andrik45719** [comment]
Done

**Comment by xyzroe** [comment]
Thanks

**Comment by mrmaximas** [comment]
> Thanks

@xyzroe How about adding the P7 x4 mod to the XZD fw?

**Comment by xyzroe** [comment]
It is already been added.

**Comment by mrmaximas** [comment]
@xyzroe 
![Screenshot 2024-07-02 at 19 12 01](https://github.com/Andrik45719/Z-Stack-firmware/assets/61165387/12444aed-c07c-45d2-af20-5888cc430886)
what should I choose for? 
Firmware	20240316
Hardware	CC2652P7

**Comment by xyzroe** [comment]
select the version you want to install

**Comment by mrmaximas** [comment]
If i select x4_20240316 then i don't see nothing about P7 in description, P2 only

**Comment by xyzroe** [comment]
Look at the file name :)

**Comment by xyzroe** [comment]
XZG shows only firmwares corresponding to the Zigbee chip model.

**Comment by mrmaximas** [comment]
> XZG shows only firmwares corresponding to the Zigbee chip model.

ok, but with description from another

**Comment by xyzroe** [comment]
For notes it uses [this file ](https://github.com/Andrik45719/Z-Stack-firmware/blob/main/README.md). If someone could change it or create another one separate for 2652P7, I'll add it to XZG. 

Full list of all firmwares with names, links, notes is located [here](https://github.com/xyzroe/XZG/blob/zb_fws/ti/manifest.json)

**Comment by mrmaximas** [comment]
> For notes it uses [this file ](https://github.com/Andrik45719/Z-Stack-firmware/blob/main/README.md). If someone could change it or create another one separate for 2652P7, I'll add it to XZG.
> 
> Full list of all firmwares with names, links, notes is located [here](https://github.com/xyzroe/XZG/blob/zb_fws/ti/manifest.json)

Thanks! 
Could you please tell me what effect can be obtained by using x4 FW? Zigbee network response speed? Something else?
One more question. When moving from P2 to P7 I flashed IEEE address from P2 to P7, is it necessary to do it when moving to P7 FW with x4 mod?

**Comment by xyzroe** [comment]
1. I don't know. I can't see any difference on my network. 
2. The content here is unrelated to the repository. It's important to clarify a common misconception: there's no need to flash the IEEE address for the CC2652. This chip does not support IEEE re-flashing. If you attempt to write to this address, the data will be written to the secondary IEEE field, while the primary field is hard-coded in the hardware.

**Comment by mrmaximas** [comment]
@xyzroe thanks!
