### ISSUE TITLE
Build based on 20240315 FW

### ISSUE THREAD

**Issue by xriser** [Andrik45719/Z-Stack-firmware#3]
Hello,

I came across the discussion about the newer, more stable firmware versions here: [GitHub Discussion on Z-Stack Firmware](https://github.com/Koenkk/Z-Stack-firmware/discussions/496). It mentions that the firmware reverting to the 6.10 SDK shows significantly better stability compared to the 20221226 and 20230305 versions, especially for large networks.

I am interested in a 460800bps modification based on the 20240315 firmware for CC2652P (slzb-06 coordinator). Could you please let me know if it’s possible to build such a version?

Thank you!

**Comment by Andrik45719** [comment]
Hi, done.
patched versions of 20240315 binaries
